-- As permissive legacy policies remain in place, add a restrictive tenant boundary
-- for authenticated users. Anon public-progress behavior is unchanged.
CREATE POLICY profiles_org_boundary ON public.profiles AS RESTRICTIVE FOR ALL TO authenticated USING (user_id = auth.uid() OR public.is_super_admin(auth.uid()) OR EXISTS (SELECT 1 FROM public.organization_members m WHERE m.user_id = profiles.user_id AND m.organization_id = public.user_organization_id(auth.uid()) AND m.status IN ('active','invited'))) WITH CHECK (user_id = auth.uid() OR public.is_super_admin(auth.uid()) OR EXISTS (SELECT 1 FROM public.organization_members m WHERE m.user_id = profiles.user_id AND m.organization_id = public.user_organization_id(auth.uid()) AND m.status IN ('active','invited')));
CREATE POLICY user_roles_org_boundary ON public.user_roles AS RESTRICTIVE FOR ALL TO authenticated USING (user_id = auth.uid() OR public.is_super_admin(auth.uid()) OR EXISTS (SELECT 1 FROM public.organization_members m WHERE m.user_id = user_roles.user_id AND m.organization_id = public.user_organization_id(auth.uid()) AND m.status IN ('active','invited'))) WITH CHECK (user_id = auth.uid() OR public.is_super_admin(auth.uid()) OR EXISTS (SELECT 1 FROM public.organization_members m WHERE m.user_id = user_roles.user_id AND m.organization_id = public.user_organization_id(auth.uid()) AND m.status IN ('active','invited')));
CREATE POLICY rdo_reports_org_boundary ON public.rdo_reports AS RESTRICTIVE FOR ALL TO authenticated USING (organization_id = public.user_organization_id(auth.uid())) WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
CREATE POLICY rdo_occurrences_org_boundary ON public.rdo_occurrences AS RESTRICTIVE FOR ALL TO authenticated USING (organization_id = public.user_organization_id(auth.uid())) WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
CREATE POLICY rdo_comments_org_boundary ON public.rdo_comments AS RESTRICTIVE FOR ALL TO authenticated USING (organization_id = public.user_organization_id(auth.uid())) WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
CREATE POLICY rdo_media_org_boundary ON public.rdo_media AS RESTRICTIVE FOR ALL TO authenticated USING (organization_id = public.user_organization_id(auth.uid())) WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
-- Physical-progress data stays publicly readable for the SECURITY INVOKER progress RPC.
-- All mutations, and non-public activity reads, are tenant-bound for signed-in users.
CREATE POLICY rdo_activities_read_boundary ON public.rdo_activities AS RESTRICTIVE FOR SELECT TO authenticated USING (organization_id = public.user_organization_id(auth.uid()) OR EXISTS (SELECT 1 FROM public.obras o WHERE o.id = rdo_activities.obra_id AND o.is_demo IS NOT TRUE));
CREATE POLICY rdo_activities_write_boundary ON public.rdo_activities AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
CREATE POLICY rdo_activities_update_boundary ON public.rdo_activities AS RESTRICTIVE FOR UPDATE TO authenticated USING (organization_id = public.user_organization_id(auth.uid())) WITH CHECK (organization_id = public.user_organization_id(auth.uid()));
CREATE POLICY rdo_activities_delete_boundary ON public.rdo_activities AS RESTRICTIVE FOR DELETE TO authenticated USING (organization_id = public.user_organization_id(auth.uid()));