// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmumfgxngzaivvyqfbed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdW1mZ3huZ3phaXZ2eXFmYmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mjc5MjksImV4cCI6MjA2ODAwMzkyOX0.az57D3U3M8roILNe52x8heM-HJb2S3gERpSaugvspK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});